### ISSUE TITLE
AndroidManifest少了配置项

### ISSUE THREAD

**Issue by Jeaung** [MEIZUPUSH/PushDemo#10]
由于停用了jcenter，demo中是以jar的方式引入sdk。但是demo的AndroidManifest.xml中少了使用jar引入需要的两个配置项目：

```
 <!-- 必要配置,提高push消息送达率 -->
        <service
            android:name="com.meizu.cloud.pushsdk.NotificationService"
            android:exported="true"/>

        <!-- 必要配置，pushSDK内部组件 -->
        <receiver android:name="com.meizu.cloud.pushsdk.SystemReceiver" >
            <intent-filter>
                <action android:name="com.meizu.cloud.pushservice.action.PUSH_SERVICE_START"/>
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>
```

在m1 note（Flyme 5.1.11.1A）上kill掉app就无法收到通知栏或者透传消息，加上这两项以后问题解决。

**Comment by comsince** [comment]
jar包集成的话，需要手动配置，如果是aar继承就不需要了，这两个组件已经集成到aar中！另外jcenter也已经恢复下载了

**Comment by Jeaung** [comment]
我的意思是，你们demo的代码需要更新，现在你们的demo用的jar的方式，但是又没有配置这两项。所以建议可以加上这两个配置，或者改为aar引入。

**Comment by comsince** [comment]
这个pushdemo是aar接入的，不需要配置这两个，你可以参考pushdemo-eclipse 版本

**Comment by Jeaung** [comment]
没问题了，我下载的是目前最新的release版3.3.170112，现在最新代码已经是aar。谢谢！

**Comment by Jeaung** [comment]
没问题了，我下载的是目前最新的release版3.3.170112，这个版本还是jar的。不过现在最新代码已经是aar。谢谢！

**Comment by comsince** [comment]
compile的时候最好指定aar下载；不然默认下载的是jar
dependencies {
        compile 'com.meizu.flyme.internet:push-internal-publish:3.3.170329@aar'
    }
