### ISSUE TITLE
通知栏小图标改为选填

### ISSUE THREAD

**Issue by Jeaung** [MEIZUPUSH/PushDemo#12]
现在新版的sdk基本上是强制要求要放置small_icon资源，但是很多使用方都是把不同厂商的几个push sdk封装成统一的组件来使用，组件无法访问外部的R.drawable。所以希望通知栏小图标如果不设置的话还是能展示旧版那个默认的图标。

**Comment by comsince** [comment]
你们打包组件是用aar吗？

**Comment by Jeaung** [comment]
是的

**Comment by comsince** [comment]
aar的话应该可以添加drawable等资源的！

**Comment by Jeaung** [comment]
问题是十几个app，不好说每个app都单独打一个aar呢

**Comment by comsince** [comment]
这个我们可以考虑优化一下！

**Comment by Jeaung** [comment]
感恩~

**Comment by recwert** [comment]
状态栏小图标的尺寸应该如何选择？我看到demo里的hdpi反而是最大的。

**Comment by comsince** [comment]
3.4.0已经解决此问题
