### ISSUE TITLE
提供清除通知栏的方法

### ISSUE THREAD

**Issue by Jeaung** [MEIZUPUSH/PushDemo#13]
有一些场景，用户可能没有通过点击push进入app，而是直接打开app。这种时候业务希望能清除这个app的通知。

**Comment by comsince** [comment]
清楚通知栏，因为没有notificationId，可能会全部清除；你们可以自己调用notificationManager.cancel（）

**Comment by Jeaung** [comment]
我们有cancelAll，但是没用

**Comment by comsince** [comment]
应该是flyme6基于android6.0以上的版本不行

**Comment by Jeaung** [comment]
像小米的sdk有提供通用的clearNotification的方法，你们能否也提供一下，会更灵活，只是建议哈。

**Comment by comsince** [comment]
clearnotification 是清楚全部通知栏，还是其中一个？

**Comment by Jeaung** [comment]
就是清除这个app的全部通知栏

**Comment by comsince** [comment]
目前暂未考虑此功能！
