### ISSUE TITLE
有些权限貌似没给的话  会报错

### ISSUE THREAD

**Issue by Leteno** [MEIZUPUSH/PushDemo#15]
java.lang.SecurityException: Neither user 10130 nor current process has android.permission.READ_PHONE_STATE.
我的设备一直没注册上，怀疑跟这次 crash 有关。

我看了用户 push 后台  貌似只有在 IMEI 查询 PushId 的时候才能用到。但是 IMEI 貌似在 Android 7.0 开始 就返回定值。所以 IMEI 并不可靠，能不能不要获取 IMEI， 或者是 在 判断没有这个权限的时候 不操作某些操作，至少不要影响注册流程，你说对吧。

**Comment by comsince** [comment]
注册必须要imei，你的应用是不是jar接入的，难道没有声明这个权限

**Comment by comsince** [comment]
pushsdk 有些权限例如联网，获取设备信息的权限是必须要加的，这些都在aar里面的androidManifest里面有声明
