### ISSUE TITLE
魅族离线推送标题长度

### ISSUE THREAD

**Issue by xulong20130712** [MEIZUPUSH/PushDemo#18]
我们测试发现，魅族的推送包体没有达到4k但是也推送不成功，华为推送包体2k华为能推送到，但是魅族推送不到，只要标题断一下就能推送到，但是标题没超过32个字符。

**Comment by comsince** [comment]
你们仅仅是推送收不到的问题吗，也可能是当前不在线造成的！对于推送通知栏消息，不管是通过flyme推送平台还是开放api，都对内容作了限制，只要推送成功，应该都能收到

**Comment by xulong20130712** [comment]
那这个怎么确定在不在线呢，怎么能确定魅族的推送通道畅通呢。

**Comment by comsince** [comment]
平台有问题排查工具，在配置管理->问题排查 模块
