### ISSUE TITLE
签名认证失败是什么原因

### ISSUE THREAD

**Issue by xuzhuo99hy** [MEIZUPUSH/PushDemo#21]
getTaskId()接口返回:
{"code":"1006","message":"签名认证失败","value":"","redirect":""}
请问可能是app_secret不对, 还是md5加密不对, 还是有其他的原因?
能给个传参的模板不, 我对接口文档里面写的sign传参不是太理解

**Comment by comsince** [comment]
这里客户端sdk，到javasdk下面提问题！
