### ISSUE TITLE
PushManager.register(context, appId, appKey) 注册无响应

### ISSUE THREAD

**Issue by radishwu** [MEIZUPUSH/PushDemo#29]
使用PushManager.register 注册无响应，当我使用错误的appid时,onRegisterStatus 回调，使用正确的appid和AppKey时，MzPushMessageReceiver无回调无响应

**Comment by radishwu** [comment]
05-27 15:48:38.601 24351-24374/com.qts.mobile.sample E/Strategy: isBrandMeizu true
05-27 15:48:38.603 24351-24374/com.qts.mobile.sample I/Strategy: current process packageName com.meizu.cloud
    send message to remote service
05-27 15:48:38.610 2082-2120/? I/System.out: open:https://api-push.meizu.com/garcia/api/client/message/registerPush
05-27 15:48:38.661 2082-2120/? I/System.out: [OkHttp] sendRequest>>
    [OkHttp] sendRequest<<
05-27 15:48:38.678 24351-24351/com.qts.mobile.sample W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-27 15:48:38.711 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f070030}
05-27 15:48:38.715 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f070007}
05-27 15:48:38.719 2082-2120/? I/NetworkManagementSocketTagger: untagSocket(43)
05-27 15:48:38.726 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f070008}
05-27 15:48:38.732 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f070006}
    Converting to string: TypedValue{t=0x5/d=0x1 a=4 r=0x7f050004}
    Converting to string: TypedValue{t=0x5/d=0x1 a=4 r=0x7f050003}
    Converting to string: TypedValue{t=0x5/d=0x3801 a=1 r=0x10500cc}
05-27 15:48:38.739 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x5/d=0x1 a=1 r=0x10500d3}
05-27 15:48:38.742 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x1/d=0x7f0d0107 a=4 r=0x7f0d0107}
    Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f07000e}
05-27 15:48:38.790 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f07003e}
05-27 15:48:38.795 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f070092}
05-27 15:48:38.799 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0700cd}
05-27 15:48:38.804 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f070027}
05-27 15:48:38.806 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f070037}
05-27 15:48:38.808 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0700c0}
05-27 15:48:38.811 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f070091}
05-27 15:48:38.826 274-378/? I/SurfaceFlinger: EventThread Client Pid (24351) created
05-27 15:48:38.829 274-957/? I/SurfaceFlinger: EventThread Client Pid (24351) created
05-27 15:48:38.832 274-22877/? I/SurfaceFlinger: [SF client] NEW(0x7f8cc7f200) for (858:system_server)
05-27 15:48:38.841 24351-24377/com.qts.mobile.sample I/SystemReceiver: com.qts.mobile.sample start register cloudVersion_name 6.4.1
05-27 15:48:38.843 24351-24377/com.qts.mobile.sample E/SystemReceiver: cloud pushService start
05-27 15:48:38.846 24351-24377/com.qts.mobile.sample E/QuickTracker: current statics domain is push-statics.meizu.com
05-27 15:48:38.852 24351-24377/com.qts.mobile.sample I/TlsSessionTicket: install tls session cache true
05-27 15:48:38.859 858-1620/? W/ActivityManager: getRunningAppProcesses: caller 10932 does not hold REAL_GET_TASKS; limiting output
05-27 15:48:38.860 24351-24377/com.qts.mobile.sample I/MzSystemUtils: processName com.qts.mobile.sample
05-27 15:48:38.899 24351-24377/com.qts.mobile.sample I/PushTracker->c: IntentReceiver|Tracker created successfully.
05-27 15:48:38.901 24351-24377/com.qts.mobile.sample I/PushAndroidTracker: can upload subject false
05-27 15:48:38.906 24351-24374/com.qts.mobile.sample I/PushTracker->e: pool-1-thread-1|Checking tracker internet connectivity.
05-27 15:48:38.913 24351-24374/com.qts.mobile.sample E/PushTracker->a: pool-1-thread-1|Emitter database empty: 1
05-27 15:48:38.956 858-928/? I/WindowManager: Gaining focus: Window{4810e71 u0 com.qts.mobile.sample/com.qts.mobile.sample.MainActivity}
05-27 15:48:38.962 24351-24376/com.qts.mobile.sample E/GED: Failed to get GED Log Buf, err(0)
05-27 15:48:38.963 24351-24376/com.qts.mobile.sample I/OpenGLRenderer: Initialized EGL, version 1.4
05-27 15:48:38.969 24351-24351/com.qts.mobile.sample W/Resources: Converting to string: TypedValue{t=0x5/d=0x2401 a=1 r=0x10500d7}
    Converting to string: TypedValue{t=0x5/d=0x3001 a=1 r=0x10500d9}
    Converting to string: TypedValue{t=0x5/d=0x601 a=1 r=0x10500d4}
    Converting to string: TypedValue{t=0x5/d=0xa01 a=1 r=0x10500d5}
05-27 15:48:38.985 274-22877/? I/[MALI][Gralloc]: Usage: 0xb00, format: 0x1 stride: 1088 vertical_stride: 1920 size: 8355840
05-27 15:48:38.986 274-22877/? I/[MALI][Gralloc]: Usage: 0xb00, format: 0x1 stride: 1088 vertical_stride: 1920 size: 8355840
05-27 15:48:38.987 274-22877/? I/[MALI][Gralloc]: Usage: 0xb00, format: 0x1 stride: 1088 vertical_stride: 1920 size: 8355840
    Usage: 0xb00, format: 0x1 stride: 1088 vertical_stride: 1920 size: 8355840
05-27 15:48:38.989 858-921/? I/libPerfService: perfSetFavorPid - pid:0, 0
05-27 15:48:39.017 24351-24376/com.qts.mobile.sample W/MALI: glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 12746
05-27 15:48:39.035 858-928/? I/ActivityManager: [AppLaunch] Displayed Displayed com.qts.mobile.sample/.MainActivity: +571ms
05-27 15:48:39.048 316-316/? I/thermal_repeater: oh, queryMdThermalInfo (0)Bad file number
05-27 15:48:39.050 858-6054/? I/libPerfService: perfSetFavorPid - pid:24351, 5f1f
05-27 15:48:39.052 316-316/? I/thermal_repeater: [recvMdThermalInfo] ret=25, strLen=127,  1, 32767,,, -1, 32767, 2
05-27 15:48:39.465 858-986/? I/libPerfService: 10: set: 4
    10: set freq: 1235000
    10: set gpu level: 0
05-27 15:48:39.514 1043-1043/? W/recents.Component: create a new LoadPlan to load thumbnail -- background
05-27 15:48:39.516 1043-1043/? W/recents.Performance: preload while task Change spend : 3
05-27 15:48:39.667 858-1396/? I/libPerfService: perfSetFavorPid - pid:0, 0
05-27 15:48:39.684 274-274/? I/SurfaceFlinger: [Built-in Screen (type:0)] fps:32.102623,dur:1246.00,max:520.85,min:11.50
05-27 15:48:39.913 24351-24374/com.qts.mobile.sample I/PushTracker->e: pool-1-thread-1|Checking tracker internet connectivity.
05-27 15:48:39.915 24351-24374/com.qts.mobile.sample E/PushTracker->a: pool-1-thread-1|Emitter database empty: 2
05-27 15:48:40.406 858-986/? I/libPerfService: 12: set: 1
    12: set freq: 0
    12: set gpu level: 0
05-27 15:48:40.702 274-274/? I/SurfaceFlinger: [Built-in Screen (type:0)] fps:0.981719,dur:1018.62,max:1018.62,min:1018.62
05-27 15:48:40.704 858-1338/? W/Watchdog: SWT Watchdog after wait current time:123114784
    **Get SF Time **1
    SWT Watchdog before synchronized:123114784
    SWT Watchdog after synchronized:123114784
05-27 15:48:40.705 858-1338/? W/Watchdog: SWT Watchdog before wait timeout:30000
    SWT Watchdog before wait current time:123114784
    SWT Watchdog before wait start:123114784
    SWT Watchdog before wait CHECK_INTERVAL:30000
05-27 15:48:40.915 24351-24374/com.qts.mobile.sample I/PushTracker->e: pool-1-thread-1|Checking tracker internet connectivity.
05-27 15:48:40.920 24351-24374/com.qts.mobile.sample E/PushTracker->a: pool-1-thread-1|Emitter loop stopping: empty limit reached.
05-27 15:48:41.450 858-986/? I/libPerfService: 7: set: 1
05-27 15:48:41.451 858-986/? I/libPerfService: 7: set freq: 0
05-27 15:48:41.992 274-274/? I/SurfaceFlinger: [Built-in Screen (type:0)] fps:1.550968,dur:1289.52,max:1281.71,min:7.80
05-27 15:48:42.145 296-947/? I/AudioFlinger: setParameters(): io 0, keyvalue mediaserver_monitor=1, calling pid 858
05-27 15:48:42.147 296-947/? W/AudioALSAHardware: setParameters(), still have param.size() = 1, remain param = "mediaserver_monitor=1"
05-27 15:48:42.147 296-947/? I/str_params: key: 'mediaserver_monitor' value: '1'
05-27 15:48:42.151 296-983/? I/AudioPolicyManager: setStreamVolumeIndex stream = 7 index = 15 device = 0x400
05-27 15:48:44.054 316-316/? I/thermal_repeater: oh, queryMdThermalInfo (0)Bad file number
05-27 15:48:44.061 316-316/? I/thermal_repeater: [recvMdThermalInfo] ret=25, strLen=127,  1, 32767,,, -1, 32767, 2
05-27 15:48:44.070 1043-1043/? I/KeyguardUpdateMonitor: handleBatteryUpdate index=0 updateInteresting=false
05-27 15:48:44.075 1339-1886/? I/BatteryConsumeMonitor: init var lastPlugType : 2 lastBatteryChangedLevel : 96
05-27 15:48:44.080 858-1616/? I/libPerfService: perfSetFavorPid - pid:24351, 5f1f
05-27 15:48:44.087 858-886/? I/libPerfService: perfSetFavorPid - pid:0, 0
05-27 15:48:44.096 858-1620/? I/libPerfService: perfSetFavorPid - pid:24351, 5f1f
05-27 15:48:44.116 274-274/? I/SurfaceFlinger: [Built-in Screen (type:0)] fps:0.470687,dur:2124.56,max:2124.56,min:2124.56
05-27 15:48:44.970 858-1424/? I/libPerfService: perfSetFavorPid - pid:0, 0

**Comment by comsince** [comment]
你把手机里面的应用推送服务数据清除掉，重新订阅

**Comment by radishwu** [comment]
@comsince 是清空应用下存储和缓存的数据吗？

**Comment by radishwu** [comment]
@comsince 手机root过有影响吗？

**Comment by comsince** [comment]
没有影响

**Comment by comsince** [comment]
你也可以下载本pushdemo编译安装看下是否订阅成功？
