### ISSUE TITLE
这是flyme推送，还是魅族推送？

### ISSUE THREAD

**Issue by Freedomhxb** [MEIZUPUSH/PushDemo#40]
这是flyme推送，还是魅族推送？还有魅族推送快速集成文档中http://open.res.flyme.cn/fileserver/upload/file/201806/0ef4484d72c04119ad103f099118a30f.pdf
Ups_PushDemo 这个demo在哪里可以看到？谢谢

**Comment by comsince** [comment]
还是在这个github里面，有一个upsdemo
