### ISSUE TITLE
通知栏图标问题

### ISSUE THREAD

**Issue by qinghui** [MEIZUPUSH/PushDemo#41]
收到魅族推送后，通知栏的图标没有使用指定的，显示的是系统默认的。
代码已经按sdk里说明修改，如下：

3.2.4 自定义通知栏小图标
PushSDK 加入了通知栏状态栏小图标自定义的功能，需要在配置的的
pushReceiver 中覆盖如下的方法：
 /**
 * 获取 smallicon
 * */
 public void onUpdateNotificationBuilder(PushNotificationBuilder
pushNotificationBuilder){
 //设置通知栏弹出的小图标

pushNotificationBuilder.setmStatusbarIcon(R.drawable.mz_push_notifica
tion_small_icon);
 };
Note: Flyme6 新的通知栏中心需要按照名称来获取状态栏 Icon,你需要在相应
的 drawable 不同分辨率文件夹下放置一个名称为
mz_push_notification_small_icon 的状态栏图标文件,请确保名称正确，否则
将无法正确显示你应用的状态栏图标

**Comment by comsince** [comment]
这个特性是在flyme6 android 6.0以后版本才生效
