### ISSUE TITLE
register成功  pushid返回

### ISSUE THREAD

**Issue by w651441914** [MEIZUPUSH/PushDemo#42]
register成功了  pushid返回 用魅族推送平台欲推送  提示非法pushid   
问题排查模块排查结果
pushid提示非法
imei提示pushId未注册

如果没有注册成功 那么pushId就不会返回才对    
求教

**Comment by ningzhaobin** [comment]
同问

**Comment by comsince** [comment]
这个可能时应用卸载，反订阅的问题，可以试着从新订阅
